"""add_seo_settings_table

Revision ID: 71944dd33360
Revises: 5a0a524368da
Create Date: 2026-05-02 13:56:36.718287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71944dd33360'
down_revision: Union[str, Sequence[str], None] = '5a0a524368da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.JSON(), server_default=sa.text('\'{"en": "Portfolio", "es": "Portafolio"}\'::jsonb'), nullable=False),
    sa.Column('description', sa.JSON(), server_default=sa.text('\'{"en": "My portfolio", "es": "Mi portafolio"}\'::jsonb'), nullable=False),
    sa.Column('keywords', sa.JSON(), server_default=sa.text('\'{"en": "developer", "es": "desarrollador"}\'::jsonb'), nullable=False),
    sa.Column('og_image', sa.String(), server_default='', nullable=True),
    sa.Column('site_url', sa.String(), server_default='', nullable=True),
    sa.Column('twitter_handle', sa.String(), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_settings_id'), 'seo_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_settings_id'), table_name='seo_settings')
    op.drop_table('seo_settings')
    # ### end Alembic commands ###
